language: generic

services:
  - docker

before_install:
  - docker build -t mfloresr12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mfloresr12/react-test npm test

after_success:
  - docker build -t mfloresr12/multi-client ./client
  - docker build -t mfloresr12/multi-nginx ./nginx
  - docker build -t mfloresr12/multi-server ./server
  - docker build -t mfloresr12/multi-worker ./worker
  # Inicie sesión en la CLI de la ventana acoplable
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tome esas imágenes y llévelas a Docker Hub
  - docker push mfloresr12/multi-client
  - docker push mfloresr12/multi-nginx
  - docker push mfloresr12/multi-server
  - docker push mfloresr12/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
